In [ ]:
# Numpy is a fundamental library for scientific computing
# It provides support for arrays, matrices along with mathematical functions to operate on these data structures

# Note :- Numpy is not installed by default, we need to install it explicitly

In [2]:
import numpy as np          # importing numpy library and using alias "np"

# creating 1D Array
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))       # type = numpy.ndarray (n-dimenstional array)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1,2,3,4,5,6])

# shape() method to get the dimension of array
print(arr.shape)       # original dimension of array
print(arr)
print()

# reshape() method to change the dimension of array (product of dimensions must be same)
# elements are reordered in row-major order
arr = arr.reshape(2,3)
print(arr.shape)
print(arr)
print()

# example of array with 3 dimensions
threeD_arr = np.array([x for x in range(8)])
threeD_arr = threeD_arr.reshape(2,2,2)
print(threeD_arr.shape)
print(threeD_arr)

(6,)
[1 2 3 4 5 6]

(2, 3)
[[1 2 3]
 [4 5 6]]

(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ones(dimensions) method to make a matrix with given dimensions initialized to 1
ones_matrix = np.ones((3,4))
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# eye(dimension) method to make a identity matrix of dimension * dimension
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# some other common methods :- ndim(), size(), dtype(), itemsize()

arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape: ", arr.shape)                     # shape of array
print("No of dimensions: ", arr.ndim)           # total dimensions of array
print("Size (no of elements): ", arr.size)      # total elements in array
print("Data type: ", arr.dtype)                 # datatype of each elenent
print("Item size (in bytes): ", arr.itemsize)   # size of each element in bytes

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
No of dimensions:  2
Size (no of elements):  6
Data type:  int64
Item size (in bytes):  8


In [3]:
# Numpy vectorized operations

arr1 = np.array([11,22,33,44,55])
arr2 = np.array([1,2,3,4,5])

# element wise addition, subttraction, multiplication and division 
# of vectors using '+', '-', '*', '/' operators respectively

print("Sum :", arr1 + arr2)
print("Difference :", arr1 - arr2)
print("Product :", arr1 * arr2)
print("Quotients :", arr1 // arr2)

Sum : [12 24 36 48 60]
Difference : [10 20 30 40 50]
Product : [ 11  44  99 176 275]
Quotients : [11 11 11 11 11]


In [40]:
# Universal Function - Applied to all elements in array
arr = np.array([1,2,3,4,5])

# square root
print(np.sqrt(arr).tolist())

# exponential       (computes e^x)
print(np.exp(arr).tolist())

# sine values (values taken as in raidans)
from math import pi
print(np.sin(pi/6*arr).tolist())

# natural log
print(np.log(arr).tolist())

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]
[2.718281828459045, 7.38905609893065, 20.085536923187668, 54.598150033144236, 148.4131591025766]
[0.49999999999999994, 0.8660254037844386, 1.0, 0.8660254037844387, 0.5000000000000003]
[0.0, 0.6931471805599453, 1.0986122886681098, 1.3862943611198906, 1.6094379124341003]


In [57]:
# array slicing and indexing    -   0 indexing is followed
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print()

# indexing is similar to inbuilt list and tuples
print(arr[0])           # print 0th row
print()
print(arr[1:])          # print row 1 onwards
print()

# slicing across columns not allowed in inbuilt python list
# must use numpy
print(arr[1:3, 0:2])       # print row 1 onwards, and first 2 columns only
print()

# modifying submatrix using slicing operation
arr[0:2, 2:] = [[20, 30], [40, 50]]     # modifying row0, row1, col2 onwards
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4]

[[ 5  6  7  8]
 [ 9 10 11 12]]

[[ 5  6]
 [ 9 10]]

[[ 1  2 20 30]
 [ 5  6 40 50]
 [ 9 10 11 12]]


In [63]:
# statistical formulas
# normalizing data using mean() and std() method
data = np.array([1, 2, 3, 4, 5])

# calulcate mean of data using mean() method
mean = np.mean(data)
print("Mean: ", mean)

# calculate standard deviation of data using std() method
std = np.std(data)
print("Standard Deviation: ", std)

normalized_data = (data - mean) / std          # using vectorized operation
print("Normalized Data: ", [round(x, 3) for x in normalized_data.tolist()])

# calulate median of data using median() method
median = np.median(data)
print("Median: ", median)

# caluclaye variance of data using var() method
variance = np.var(data)
print("Variance: ", variance)

Mean:  3.0
Standard Deviation:  1.4142135623730951
Normalized Data:  [-1.414, -0.707, 0.0, 0.707, 1.414]
Median:  3.0
Variance:  2.0


In [ ]:
# logical operation
# used for filtering the data
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

filter1 = data <= 4             # returns a boolean array stating whether
filter2 = data >= 7             # the element satisfies the given condition

print(filter1)  
print(filter2)

finalfilter = filter1 | filter2 # perform logical operation on boolean arrays
print(finalfilter)              # true means include the element otherwise exclude

print(data[finalfilter].tolist())        # give boolean array as index to array

[ True  True  True  True False False False False False False]
[False False False False False False  True  True  True  True]
[ True  True  True  True False False  True  True  True  True]
[1, 2, 3, 4, 7, 8, 9, 10]
